coverage:
  round: nearest
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
        informational: true # this will always allow the status check to pass
        branches:
          - main
        if_ci_failed: error
        flags:
          - unit
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error
        flags:
          - unit
        informational: true # this will always allow the status check to pass
ignore:
  - internal/ent/generated/**
  - internal/datumclient/**
  - query/**
  - schema/**
  - scripts/**
  - gen_schema.go
  - generate.go
  - tools.go
  - docker/**
  - db/**
comment:
  layout: diff, files
  require_changes: true