version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - serve
      - --debug
      - --pretty
      - --dev
    ports:
      - "17608:17608"
    restart: unless-stopped
    networks:
      - default
