version: '3'

includes:
  cli: ./cli
  docker: ./docker
  fga: ./fga
  db: ./db

env:
  ATLAS_DB_URI: "sqlite://file?mode=memory&_fk=1"
  TEST_DB_URL: "sqlite://file:ent?mode=memory&cache=shared&_fk=1"
  TEST_FGA_URL: "localhost:8080"
  ENV: config

tasks:
  install:
    desc: installs tools and packages needed to develop against the datum repo
    cmds:
      - "go install github.com/hairyhenderson/gomplate/v4/cmd/gomplate@latest"
      - "go install entgo.io/ent/cmd/ent@latest"
      - "go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest"
      - "curl -sSf https://atlasgo.sh | sh"
      - "curl -sSL https://rover.apollo.dev/nix/latest | sh"
      - "go get -u github.com/openfga/go-sdk"
      - "brew install openfga/tap/fga"
      - "go install go.uber.org/mock/mockgen@latest"
      - defer: { task: go:tidy }

  ## Generate tasks
  ent:
    desc: runs go generate against ent schema - see the entc.go file and generates the fga mock client
    cmds:
      - go generate ./...

  gqlgen:
    desc: runs gqlgen and gqlgenc commands using gen_generate.go and entc
    cmds:
      - go run github.com/99designs/gqlgen generate --verbose
      - task: tidy
      - go run ./gen_schema.go
      - go run github.com/Yamashou/gqlgenc generate --configdir schema

  generate:
    desc: a combination of the ent, graph, and gqlgen tasks which are required to fully generate the necessary graph, server, resolvers, client, etc. 
    cmds:
      - task: ent
      - task: gqlgen
      - cp ./internal/ent/generated/openapi.json ./internal/httpserve/route

  clean:generated:
    desc: cleans ent / gqlgen generated files to be re-generated
    cmds:
      - |
        echo "Enter the name of the ent schema object name to clean:"
        read clean;
        go run ./internal/entclean/main.go --path=internal/ent ${clean};
      - "rm -f schema/ent.graphql"
      - "rm -f schema.graphql"
      - "rm -rf internal/datumclient/"

  ## Go tasks
  go:lint:
    desc: runs golangci-lint, the most annoying opinionated linter ever
    cmds:
      - golangci-lint run -v

  go:test:
    desc: runs and outputs results of created go tests
    cmds:
      - go test -v ./...

  go:tidy:
    desc: Runs go mod tidy on the backend
    aliases: [tidy]
    cmds:
      - go mod tidy

  go:build:
    desc: Runs go build for the datum server
    cmds:
      - go build -mod=mod -o datum

  go:build-cli:
    aliases: [buildcli]
    desc: Runs go build for the datum cli
    cmds:
      - go build -mod=mod -o datum-cli ./cmd/cli 

  go:all:
    aliases: [go]
    desc: Runs all go test and lint related tasks
    cmds:
      - task: go:tidy
      - task: go:lint
      - task: go:test

 
  # dev tasks
  pr:
    desc: runs the comprehensive roll-up tasks required to ensure all files are being committed / pushed as a part of opening a PR 
    cmds:
      - task: generate
      - task: atlas
      - task: go
      - task: fga:test

  ci:
    desc: a task that runs during CI
    cmds:
      - task: ent
      - task: gqlgen
      - task: tidy
      - "git config --global --add safe.directory /workdir"
      - |
        status=$(git status --porcelain)
        if [ -n "$status" ]; then
        echo "detected git diff after running generate; please re-run tasks"
        echo "$status"
        exit 1
        fi

  clean:local:
    desc: cleans up datum.db and datum-cli local
    cmds:
      - "rm -f datum.db"
      - "rm -f datum-cli"

  shell:
    desc: open a new shell to launch server as a dep
    cmds:
      - rm -f datum.db
      - rm -f datum-cli
      - osascript -e 'tell app "Terminal" to do script "cd {{.PWD}} && task run-dev"'
    vars:
      PWD:
        sh: pwd
      
