package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"
)

// PostEvent is the resolver for the postEvent field.
func (r *mutationResolver) PostEvent(ctx context.Context, message string) (string, error) {

	// r.client.PublishEvent(ctx, message)
	// return message, nil

	panic(fmt.Errorf("not implemented: PostEvent - postEvent"))
}
