package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"fmt"

	"github.com/datumforge/datum/internal/ent/generated"
)

// CreateGroupSettings is the resolver for the createGroupSettings field.
func (r *createGroupInputResolver) CreateGroupSettings(ctx context.Context, obj *generated.CreateGroupInput, data *generated.CreateGroupSettingInput) error {
	panic(fmt.Errorf("not implemented: CreateGroupSettings - createGroupSettings"))
}

// AddGroupMembers is the resolver for the addGroupMembers field.
func (r *updateGroupInputResolver) AddGroupMembers(ctx context.Context, obj *generated.UpdateGroupInput, data []*generated.CreateGroupMembershipInput) error {
	panic(fmt.Errorf("not implemented: AddGroupMembers - addGroupMembers"))
}

// UpdateGroupSettings is the resolver for the updateGroupSettings field.
func (r *updateGroupInputResolver) UpdateGroupSettings(ctx context.Context, obj *generated.UpdateGroupInput, data *generated.UpdateGroupSettingInput) error {
	panic(fmt.Errorf("not implemented: UpdateGroupSettings - updateGroupSettings"))
}
