package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/datumforge/datum/internal/ent/generated"
)

// CreateHush is the resolver for the createHush field.
func (r *mutationResolver) CreateHush(ctx context.Context, input generated.CreateHushInput) (*HushCreatePayload, error) {
	panic(fmt.Errorf("not implemented: CreateHush - createHush"))
}

// UpdateHush is the resolver for the updateHush field.
func (r *mutationResolver) UpdateHush(ctx context.Context, id string, input generated.UpdateHushInput) (*HushUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: UpdateHush - updateHush"))
}

// DeleteHush is the resolver for the deleteHush field.
func (r *mutationResolver) DeleteHush(ctx context.Context, id string) (*HushDeletePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteHush - deleteHush"))
}

// Hush is the resolver for the hush field.
func (r *queryResolver) Hush(ctx context.Context, id string) (*generated.Hush, error) {
	panic(fmt.Errorf("not implemented: Hush - hush"))
}
