package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/datumforge/datum/internal/ent/generated"
	"github.com/datumforge/datum/pkg/rout"
)

// CreateInvite is the resolver for the createInvite field.
func (r *mutationResolver) CreateInvite(ctx context.Context, input generated.CreateInviteInput) (*InviteCreatePayload, error) {
	// set the organization in the auth context if its not done for us
	if err := setOrganizationInAuthContext(ctx, input.OwnerID); err != nil {
		r.logger.Errorw("failed to set organization in auth context", "error", err)

		return nil, rout.NewMissingRequiredFieldError("owner_id")
	}

	om, err := withTransactionalMutation(ctx).Invite.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionCreate, object: "invite"}, r.logger)
	}

	return &InviteCreatePayload{Invite: om}, nil
}

// CreateBulkInvite is the resolver for the createBulkInvite field.
func (r *mutationResolver) CreateBulkInvite(ctx context.Context, input []*generated.CreateInviteInput) (*InviteBulkCreatePayload, error) {
	return r.bulkCreateInvite(ctx, input)
}

// CreateBulkCSVInvite is the resolver for the createBulkCSVInvite field.
func (r *mutationResolver) CreateBulkCSVInvite(ctx context.Context, input graphql.Upload) (*InviteBulkCreatePayload, error) {
	data, err := unmarshalBulkData[generated.CreateInviteInput](input)
	if err != nil {
		r.logger.Errorw("failed to unmarshal bulk data", "error", err)

		return nil, err
	}

	return r.bulkCreateInvite(ctx, data)
}

// UpdateInvite is the resolver for the updateInvite field.
func (r *mutationResolver) UpdateInvite(ctx context.Context, id string, input generated.UpdateInviteInput) (*InviteUpdatePayload, error) {
	invite, err := withTransactionalMutation(ctx).Invite.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionUpdate, object: "invite"}, r.logger)
	}

	if err := setOrganizationInAuthContext(ctx, &invite.OwnerID); err != nil {
		r.logger.Errorw("failed to set organization in auth context", "error", err)

		return nil, ErrPermissionDenied
	}

	invite, err = invite.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionUpdate, object: "invite"}, r.logger)
	}

	return &InviteUpdatePayload{Invite: invite}, nil
}

// DeleteInvite is the resolver for the deleteInvite field.
func (r *mutationResolver) DeleteInvite(ctx context.Context, id string) (*InviteDeletePayload, error) {
	if err := withTransactionalMutation(ctx).Invite.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, parseRequestError(err, action{action: ActionDelete, object: "invite"}, r.logger)
	}

	if err := generated.InviteEdgeCleanup(ctx, id); err != nil {
		return nil, newCascadeDeleteError(err)
	}

	return &InviteDeletePayload{DeletedID: id}, nil
}

// Invite is the resolver for the invite field.
func (r *queryResolver) Invite(ctx context.Context, id string) (*generated.Invite, error) {
	inv, err := withTransactionalMutation(ctx).Invite.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionGet, object: "invite"}, r.logger)
	}

	return inv, nil
}
