package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/datumforge/datum/internal/ent/generated"
	"github.com/datumforge/datum/pkg/rout"
)

// CreateNote is the resolver for the createNote field.
func (r *mutationResolver) CreateNote(ctx context.Context, input generated.CreateNoteInput) (*NoteCreatePayload, error) {
	// set the organization in the auth context if its not done for us
	if err := setOrganizationInAuthContext(ctx, input.OwnerID); err != nil {
		r.logger.Errorw("failed to set organization in auth context", "error", err)

		return nil, rout.NewMissingRequiredFieldError("owner_id")
	}

	res, err := withTransactionalMutation(ctx).Note.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionCreate, object: "note"}, r.logger)
	}

	return &NoteCreatePayload{
		Note: res,
	}, nil
}

// CreateBulkNote is the resolver for the createBulkNote field.
func (r *mutationResolver) CreateBulkNote(ctx context.Context, input []*generated.CreateNoteInput) (*NoteBulkCreatePayload, error) {
	return r.bulkCreateNote(ctx, input)
}

// CreateBulkCSVNote is the resolver for the createBulkCSVNote field.
func (r *mutationResolver) CreateBulkCSVNote(ctx context.Context, input graphql.Upload) (*NoteBulkCreatePayload, error) {
	data, err := unmarshalBulkData[generated.CreateNoteInput](input)
	if err != nil {
		r.logger.Errorw("failed to unmarshal bulk data", "error", err)

		return nil, err
	}

	return r.bulkCreateNote(ctx, data)
}

// UpdateNote is the resolver for the updateNote field.
func (r *mutationResolver) UpdateNote(ctx context.Context, id string, input generated.UpdateNoteInput) (*NoteUpdatePayload, error) {
	res, err := withTransactionalMutation(ctx).Note.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionUpdate, object: "note"}, r.logger)
	}
	// set the organization in the auth context if its not done for us
	if err := setOrganizationInAuthContext(ctx, &res.OwnerID); err != nil {
		r.logger.Errorw("failed to set organization in auth context", "error", err)

		return nil, ErrPermissionDenied
	}

	// setup update request
	req := res.Update().SetInput(input).AppendTags(input.AppendTags)

	res, err = req.Save(ctx)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionUpdate, object: "note"}, r.logger)
	}

	return &NoteUpdatePayload{
		Note: res,
	}, nil
}

// DeleteNote is the resolver for the deleteNote field.
func (r *mutationResolver) DeleteNote(ctx context.Context, id string) (*NoteDeletePayload, error) {
	if err := withTransactionalMutation(ctx).Note.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, parseRequestError(err, action{action: ActionDelete, object: "note"}, r.logger)
	}

	if err := generated.NoteEdgeCleanup(ctx, id); err != nil {
		return nil, newCascadeDeleteError(err)
	}

	return &NoteDeletePayload{
		DeletedID: id,
	}, nil
}

// Note is the resolver for the note field.
func (r *queryResolver) Note(ctx context.Context, id string) (*generated.Note, error) {
	res, err := withTransactionalMutation(ctx).Note.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionGet, object: "note"}, r.logger)
	}

	return res, nil
}
