package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/datumforge/datum/internal/ent/generated"
)

// CreateSubscribers is the resolver for the createSubscribers field.
func (r *mutationResolver) CreateSubscribers(ctx context.Context, input generated.CreateSubscribersInput) (*SubscribersCreatePayload, error) {
	panic(fmt.Errorf("not implemented: CreateSubscribers - createSubscribers"))
}

// UpdateSubscribers is the resolver for the updateSubscribers field.
func (r *mutationResolver) UpdateSubscribers(ctx context.Context, id string, input generated.UpdateSubscribersInput) (*SubscribersUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: UpdateSubscribers - updateSubscribers"))
}

// DeleteSubscribers is the resolver for the deleteSubscribers field.
func (r *mutationResolver) DeleteSubscribers(ctx context.Context, id string) (*SubscribersDeletePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteSubscribers - deleteSubscribers"))
}

// Subscribers is the resolver for the subscribers field.
func (r *queryResolver) Subscribers(ctx context.Context, id string) (*generated.Subscribers, error) {
	panic(fmt.Errorf("not implemented: Subscribers - subscribers"))
}
