package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/datumforge/datum/internal/ent/generated"
)

// CreateSubscriber is the resolver for the createSubscriber field.
func (r *mutationResolver) CreateSubscriber(ctx context.Context, input generated.CreateSubscriberInput) (*SubscriberCreatePayload, error) {
	panic(fmt.Errorf("not implemented: CreateSubscriber - createSubscriber"))
}

// UpdateSubscriber is the resolver for the updateSubscriber field.
func (r *mutationResolver) UpdateSubscriber(ctx context.Context, id string, input generated.UpdateSubscriberInput) (*SubscriberUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: UpdateSubscriber - updateSubscriber"))
}

// DeleteSubscriber is the resolver for the deleteSubscriber field.
func (r *mutationResolver) DeleteSubscriber(ctx context.Context, id string) (*SubscriberDeletePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteSubscriber - deleteSubscriber"))
}

// Subscriber is the resolver for the subscriber field.
func (r *queryResolver) Subscriber(ctx context.Context, id string) (*generated.Subscriber, error) {
	panic(fmt.Errorf("not implemented: Subscriber - subscriber"))
}
