package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"errors"

	"github.com/99designs/gqlgen/graphql"
	"github.com/datumforge/datum/internal/ent/generated"
	_ "github.com/datumforge/datum/internal/ent/generated/runtime"
	"github.com/datumforge/datum/pkg/auth"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input generated.CreateUserInput) (*UserCreatePayload, error) {
	// TODO: look at allowing this resolver to invite the user instead of creating them directly
	// for now, return permission denied
	return nil, ErrPermissionDenied
}

// CreateBulkUser is the resolver for the createBulkUser field.
func (r *mutationResolver) CreateBulkUser(ctx context.Context, input []*generated.CreateUserInput) (*UserBulkCreatePayload, error) {
	return r.bulkCreateUser(ctx, input)
}

// CreateBulkCSVUser is the resolver for the createBulkCSVUser field.
func (r *mutationResolver) CreateBulkCSVUser(ctx context.Context, input graphql.Upload) (*UserBulkCreatePayload, error) {
	data, err := unmarshalBulkData[generated.CreateUserInput](input)
	if err != nil {
		r.logger.Errorw("failed to unmarshal bulk data", "error", err)

		return nil, err
	}

	return r.bulkCreateUser(ctx, data)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input generated.UpdateUserInput) (*UserUpdatePayload, error) {
	user, err := withTransactionalMutation(ctx).User.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionUpdate, object: "user"}, r.logger)
	}

	user, err = user.Update().SetInput(input).Save(ctx)
	if err != nil {
		// the password field is encrypted so we cannot use the
		// built in validation function/validation error
		if errors.Is(err, auth.ErrPasswordTooWeak) {
			return nil, err
		}

		return nil, parseRequestError(err, action{action: ActionUpdate, object: "user"}, r.logger)
	}

	return &UserUpdatePayload{User: user}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*UserDeletePayload, error) {
	if err := withTransactionalMutation(ctx).User.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, parseRequestError(err, action{action: ActionDelete, object: "user"}, r.logger)
	}

	if err := generated.UserEdgeCleanup(ctx, id); err != nil {
		return nil, newCascadeDeleteError(err)
	}

	return &UserDeletePayload{DeletedID: id}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*generated.User, error) {
	user, err := withTransactionalMutation(ctx).User.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionGet, object: "user"}, r.logger)
	}

	return user, nil
}
