package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/datumforge/datum/internal/ent/generated"
)

// CreateWebhook is the resolver for the createWebhook field
func (r *mutationResolver) CreateWebhook(ctx context.Context, input generated.CreateWebhookInput) (*WebhookCreatePayload, error) {
	webhook, err := withTransactionalMutation(ctx).Webhook.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionCreate, object: "webhook"}, r.logger)
	}

	return &WebhookCreatePayload{Webhook: webhook}, nil
}

// CreateBulkWebhook is the resolver for the createBulkWebhook field.
func (r *mutationResolver) CreateBulkWebhook(ctx context.Context, input []*generated.CreateWebhookInput) (*WebhookBulkCreatePayload, error) {
	return r.bulkCreateWebhook(ctx, input)
}

// CreateBulkCSVWebhook is the resolver for the createBulkCSVWebhook field.
func (r *mutationResolver) CreateBulkCSVWebhook(ctx context.Context, input graphql.Upload) (*WebhookBulkCreatePayload, error) {
	data, err := unmarshalBulkData[generated.CreateWebhookInput](input)
	if err != nil {
		r.logger.Errorw("failed to unmarshal bulk data", "error", err)

		return nil, err
	}

	return r.bulkCreateWebhook(ctx, data)
}

// UpdateWebhook is the resolver for the updateWebhook field
func (r *mutationResolver) UpdateWebhook(ctx context.Context, id string, input generated.UpdateWebhookInput) (*WebhookUpdatePayload, error) {
	webhook, err := withTransactionalMutation(ctx).Webhook.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionUpdate, object: "webhook"}, r.logger)
	}

	webhook, err = webhook.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionUpdate, object: "webhook"}, r.logger)
	}

	return &WebhookUpdatePayload{Webhook: webhook}, nil
}

// DeleteWebhook is the resolver for the deleteWebhook field
func (r *mutationResolver) DeleteWebhook(ctx context.Context, id string) (*WebhookDeletePayload, error) {
	if err := withTransactionalMutation(ctx).Webhook.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, parseRequestError(err, action{action: ActionDelete, object: "webhook"}, r.logger)
	}

	if err := generated.WebhookEdgeCleanup(ctx, id); err != nil {
		return nil, newCascadeDeleteError(err)
	}

	return &WebhookDeletePayload{DeletedID: id}, nil
}

// Webhook is the resolver for the webhook field
func (r *queryResolver) Webhook(ctx context.Context, id string) (*generated.Webhook, error) {
	webhook, err := withTransactionalMutation(ctx).Webhook.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionGet, object: "webhook"}, r.logger)
	}

	return webhook, nil
}
