// Code generated by enthistory, DO NOT EDIT.
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"

	"github.com/flume/enthistory"

	"time"
)

// EntitlementHistory holds the schema definition for the EntitlementHistory entity.
type EntitlementHistory struct {
	ent.Schema
}

// Annotations of the EntitlementHistory.
func (EntitlementHistory) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{
			Table: "entitlement_history",
		},
        enthistory.Annotations{
            IsHistory: true,
            Exclude: true,
        },
	}
}

// Fields of the EntitlementHistory.
func (EntitlementHistory) Fields() []ent.Field {
	historyFields := []ent.Field{
        field.Time("history_time").
            Default(time.Now).
            Immutable(),
        field.String("ref").
            Immutable().
            Optional(),
        field.Enum("operation").
            GoType(enthistory.OpType("")).
            Immutable(),
    }


    original := Entitlement{}
    for _, field := range original.Fields() {
        if field.Descriptor().Name != "id" {
            historyFields = append(historyFields, field)
        }
    }

    return historyFields
}

// Mixin of the EntitlementHistory.
func (EntitlementHistory) Mixin() []ent.Mixin {
	return Entitlement{}.Mixin()
}
