// Code generated by enthistory, DO NOT EDIT.
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"

	"github.com/flume/enthistory"

    "github.com/datumforge/datum/internal/entx"

	"time"
)

// UserHistory holds the schema definition for the UserHistory entity.
type UserHistory struct {
	ent.Schema
}

// Annotations of the UserHistory.
func (UserHistory) Annotations() []schema.Annotation {
	return []schema.Annotation{
        entx.SchemaGenSkip(true),
		entsql.Annotation{
			Table: "user_history",
		},
        enthistory.Annotations{
            IsHistory: true,
            Exclude: true,
        },
	}
}

// Fields of the UserHistory.
func (UserHistory) Fields() []ent.Field {
	historyFields := []ent.Field{
        field.Time("history_time").
            Default(time.Now).
            Immutable(),
        field.String("ref").
            Immutable().
            Optional(),
        field.Enum("operation").
            GoType(enthistory.OpType("")).
            Immutable(),
    }

    // get the fields from the mixins
    mixins := User{}.Mixin()
    for _, mixin  := range mixins {
        for _, field := range mixin.Fields() {
            historyFields = append(historyFields, field)
        }
    }

    original := User{}
    for _, field := range original.Fields() {
        historyFields = append(historyFields, field)
    }

    return historyFields
}
func (UserHistory) Indexes() []ent.Index {
	return []ent.Index{
        index.Fields("history_time"),
	}
}
