---
openapi: 3.1.0
info:
    title: Datum OpenAPI 3.1.0 Specifications
    description: Documentation for Datum's API services
    termsOfService: https://datum.net/terms
    contact:
        name: Datum Support
        url: https://datum.net/support
        email: support@datum.net
    license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0.html
    version: 1.0.1
servers:
    - url: http://localhost:17608/v1
    - url: https://api.datum.net/v1
paths:
    /ready:
        get:
            operationId: readyID
            security:
                - {}
            summary: Status Check
            description: A status check for the server and it's associated dependencies
            responses:
                "400":
                    description: Bad Request
                "200":
                    description: The status of the server and sub components are returned
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    fga:
                                        type: string
                                    redis:
                                        type: string
                                    sqlite_db_primary:
                                        type: string
    /livez:
        get:
            operationId: liveID
            security:
                - {}
            summary: Server liveness check response
            description: A heartbeat check to confirm the server is up or down
            responses:
                "400":
                    description: Bad Request
                "200":
                    description: An up / down status of the server is returned
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: the response HTTP code also in the response payload for your
            parsing convenience
        reply:
          type: object
          description: the Reply generated via the internal/rout package which contains
            a success bool and the corresponding message
          properties:
            error:
              type: string
              description: The error message if the request was unsuccessful
            success:
              type: boolean
              description: Whether or not the request was successful or not
            unverified:
              type: boolean
    v1.PubkeyRequest:
      type: object
      properties:
        body:
          type: string
          description: Add a public part of a SSH key pair.
        name:
          type: string
          description: Enter the name of the newly created pubkey.
    v1.PubkeyResponse:
      type: object
      properties:
        body:
          type: string
        fingerprint:
          type: string
        fingerprint_legacy:
          type: string
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
  parameters:
    Limit:
      name: limit
      in: query
      description: The number of items to return.
      schema:
        type: integer
        default: 100
  responses:
    BadRequest:
      description: The request's parameters are not valid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            error:
              value:
                code: 400
                reply:
                  success: false
                  error: bad request
  examples:
    v1.GenericExample:
      value:
        error: 'error: this can be pretty long string'
        version: df8a489
        environment: ""
