agents:
  tag: funk

env: 
  CI: true

steps:
- group: ":database: atlas lint + migrate"
  key: "atlas"
  steps:
  - label: ":sqlite: atlas"
    key: "sqlite"
    plugins:
      - datumforge/atlas#34f5307146d6c6535f5f90538163f5c28f566be4:
          project: datum
          dev-url: "sqlite://dev?mode=memory&_fk=1"
          dir: "file://db/migrations"
          step: all