agents:
  tag: funk

env: 
  CI: true

steps:
- group: ":database: atlas lint + migrate"
  key: "atlas"
  steps:
  - label: ":sqlite: atlas"
    key: "sqlite"
    plugins:
      - datumforge/atlas#bfeec782bacb48263c648c62a9def3a3cd9e8e57:
          project: datum
          dev-url: "sqlite://dev?mode=memory&_fk=1"
          dir: "file://db/migrations"
          step: all