package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/datumforge/datum/internal/ent/generated"
)

// CreateTaco is the resolver for the createTaco field.
func (r *mutationResolver) CreateTaco(ctx context.Context, input generated.CreateTacoInput) (*TacoCreatePayload, error) {
	panic(fmt.Errorf("not implemented: CreateTaco - createTaco"))
}

// UpdateTaco is the resolver for the updateTaco field.
func (r *mutationResolver) UpdateTaco(ctx context.Context, id string, input generated.UpdateTacoInput) (*TacoUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: UpdateTaco - updateTaco"))
}

// DeleteTaco is the resolver for the deleteTaco field.
func (r *mutationResolver) DeleteTaco(ctx context.Context, id string) (*TacoDeletePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteTaco - deleteTaco"))
}

// Taco is the resolver for the taco field.
func (r *queryResolver) Taco(ctx context.Context, id string) (*generated.Taco, error) {
	panic(fmt.Errorf("not implemented: Taco - taco"))
}
