version: "3.9"
services:
  api:
    depends_on:
      - openfga
    env_file:
      - ../config/.env.devauth
    environment:
      DATUM_AUTHZ_HOST: openfga:8080
    command:
      - serve
      - --debug
      - --pretty
