version: "3.9"
services:
  api:
    depends_on:
      - openfga
    command:
      - serve
      - --dev
      - --debug
      - --pretty
      - --auth=true
      - --fga-host=openfga:8080
      - --fga-scheme=http
