version: "3.9"
services:
  api:
    depends_on:
      - openfga
    env_file:
      - ../config/.env-devauth
    environment:
      DATUM_AUTHZ_HOST: openfga:8080
      DATUM_REDIS_ADDRESS: redis:6379
      DATUM_SEND_GRID_API_KEY: "THIS_IS_A_FAKE_KEY"
    command:
      - serve
      - --debug
      - --pretty
