version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command:
      - serve
      - --debug
      - --pretty
      - --dev
      - --auth=false
    ports:
      - "17608:17608"
    restart: unless-stopped
    environment:
      - DATUM_SEND_GRID_API_KEY="THIS_IS_A_FAKE_KEY"
    networks:
      - default
