# dev configuration for an auth enabled datum server
# echo server config settings
server:
  # logging settings
  logging:
    # log level, defaults to info, set to true to for debug level logs
    debug: true
    # pretty, human readable logs to be used during development 
    pretty: true
  # enables dev settings such as apollo graph playground
  dev: true
  # port to api to listen, defaults to :17608 
  listen: 
  # enable https settings
  https: false
  # ssl cert file location
  ssl-cert:
  # ssl key file location
  ssl-key: 
  # automatically generate tls cert instead of providing the ssl-cert and key
  auto-cert:
  # host to use to generate tls cert
  cert-host:
  # server shutdown grace period in seconds before forcefully killing
  shutdown-grace-period: 10s
  # interval to refresh the server config, defaults to 10 minutes
  config-refresh:

# database settings
db:
  # write all transactions to both a primary and secondary database backend
  multi-write: false
  # uri of primary sqlite database, required, defaults to datum.db?mode=memory&_fk=1
  primary: 
  # uri of secondary sqlite database, optional, defaults to backup.db?mode=memory&_fk=1
  secondary: 

# authentication and authorization settings
auth: true # enables authentication checks
jwt:
  # expected audience of datum JWT
  audience: http://localhost:17608
  # expected issuer of datum JWT
  issuer:  http://localhost:17608
  # cookie domain for datum JWT, defaults to datum.net
  cookie-domain: localhost:17608
  # id for the JWT keys
  kid: 01HHAS67AM73778S0QEZ3CEAGE
  # timeout for remote JWKS fetching, defaults to 5 minutes
  remote-timeout:
  # length of time the access token is valid, defaults to 1 hour
  access-duration:
  # length of time the refresh token is valid, defaults to 2 hours
  refresh-duration:
  # overlap duration between refresh and access token expiration, defaults to 15 minutes
  refresh-overlap:
fga:
  # fga host without the scheme (e.g. api.fga.example instead of https://api.fga.example)
  host: localhost:8080
  # fga scheme (http vs. https)
  scheme: http
  # fga store
  store:
    # existing store id, leave empty to create one automatically
    id: 
  # fga model ID
  model:
    # existing model id, leave empty to create one automatically
    id: 
    # force create a new model, even if one already exists
    create:

