# server settings
server:
  debug: true
  dev: true

  # tls settings
  tls:
    enabled: false

# db settings
db:
  debug: true
  multiWrite: false

# auth settings
auth:
  enabled: true
  token:
    kid: "02GGBS68AM12178M0REW3CEAFF"
  supportedProviders:
    - google
    - github
  providers:
    google:
      scopes:
        - email
        - profile
    github:
      scopes:
        - user:email
        - read:user
    webauthn:
      debug: false
      enabled: true
      relyingPartyId: "api.datum.net"
      requestOrigin: "https://console.datum.net"

# authz settings
authz:
  enabled: true
  storeName: datum
  createNewModel: false

# session settings
sessions:
  signingKey: "4N0txRe4PSBTIGhXpMEriFlfDEH9zTri"
  encryptionKey: "IF841pLk48ibOVo6w9UIkr9OBCkjXG2q"

# email settings
email:
  testing: false
  consoleUrl:
    consoleBase: "https://console.datum.net"

# sentry settings
sentry:
  enabled: true

# analytics settings
posthog:
  enabled: true
