# server settings
server:
  debug: true
  dev: true
  cors:
    allowOrigins:
      - http://localhost:3001
      - http://localhost:5500
  # tls settings
  tls:
    enabled: false
# db settings
db:
  debug: true
  driverName: libsql
  primaryDbSource: "file:datum.db"
  multiWrite: false
# auth settings
auth:
  enabled: true
  token:
    kid: "02GGBS68AM12178M0REW3CEAFF"
    audience: "http://localhost:17608"
    refreshAudience: "http://localhost:17608"
    issuer: "http://localhost:17608"
    jwksEndpoint: "http://localhost:17608/.well-known/jwks.json"
  supportedProviders:
    - google
    - github
  providers:
    google:
      clientId: "client_id_here.apps.googleusercontent.com"
      clientSecret: "client_secret_here"
      scopes:
        - email
        - profile
    github:
      clientId: "client_id_here"
      clientSecret: "client_secret_here"
      scopes:
        - user:email
        - read:user
    webauthn:
      debug: false
      enabled: true
      relyingPartyId: "localhost"
      requestOrigin: "http://localhost:3001"
# authz settings
authz:
  enabled: true
  storeName: datum
  hostUrl: http://localhost:8080
  createNewModel: false
# session settings
sessions:
  signingKey: "4N0txRe4PSBTIGhXpMEriFlfDEH9zTri"
  encryptionKey: "IF841pLk48ibOVo6w9UIkr9OBCkjXG2q"
# email settings
email:
  testing: true
  archive: "fixtures/email"
  sendGridApiKey: "SG.FakeAPIKey"
  consoleUrl:
    consoleBase: "http://localhost:17608/"
# sentry settings
sentry:
  enabled: false
  dsn: "https://fake.ingest.sentry.io/fake"
# analytics settings
posthog:
  enabled: false
  apiKey: "phc_FakeKey"
