---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . -}}-config
  {{ $labels := include "common.tplvalues.merge" (dict "values" ( list .Values.api.commonLabels (include "common.labels.standard" .) ) "context" . ) }}
  labels: {{- include "common.tplvalues.render" ( dict "value" $labels "context" $) | nindent 4 }}
  {{- if .Values.api.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.api.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
data:
  DATUM_REFRESHINTERVAL: {{ .Values.datum.refreshInterval | default "10m" }}
  DATUM.SERVER_DEBUG: {{ .Values.datum.server.debug | default false }}
  DATUM.SERVER_DEV: {{ .Values.datum.server.dev | default false }}
  DATUM.SERVER_LISTEN: {{ .Values.datum.server.listen | default ":17608" }}
  DATUM.SERVER_SHUTDOWNGRACEPERIOD: {{ .Values.datum.server.shutdownGracePeriod | default "10s" }}
  DATUM.SERVER_READTIMEOUT: {{ .Values.datum.server.readTimeout | default "15s" }}
  DATUM.SERVER_WRITETIMEOUT: {{ .Values.datum.server.writeTimeout | default "15s" }}
  DATUM.SERVER_IDLETIMEOUT: {{ .Values.datum.server.idleTimeout | default "30s" }}
  DATUM.SERVER_READHEADERTIMEOUT: {{ .Values.datum.server.readHeaderTimeout | default "2s" }}
  DATUM.SERVER.TLS_ENABLED: {{ .Values.datum.server.tls.enabled | default false }}
  DATUM.SERVER.TLS_CERTFILE: {{ .Values.datum.server.tls.certFile | default "server.crt" }}
  DATUM.SERVER.TLS_CERTKEY: {{ .Values.datum.server.tls.certKey | default "server.key" }}
  DATUM.SERVER.TLS_AUTOCERT: {{ .Values.datum.server.tls.autoCert | default false }}
  DATUM.SERVER.CORS_ENABLED: {{ .Values.datum.server.cors.enabled | default true }}
  DATUM.SERVER.CORS_PREFIXES: {{ .Values.datum.server.cors.prefixes }}
  DATUM.SERVER.CORS_ALLOWORIGINS: {{ .Values.datum.server.cors.allowOrigins }}
  DATUM.SERVER.CORS_COOKIEINSECURE: {{ .Values.datum.server.cors.cookieInsecure }}
  DATUM.SERVER.SECURE_ENABLED: {{ .Values.datum.server.secure.enabled | default true }}
  DATUM.SERVER.SECURE_XSSPROTECTION: {{ .Values.datum.server.secure.xssprotection | default "1; mode=block" }}
  DATUM.SERVER.SECURE_CONTENTTYPENOSNIFF: {{ .Values.datum.server.secure.contenttypenosniff | default "nosniff" }}
  DATUM.SERVER.SECURE_XFRAMEOPTIONS: {{ .Values.datum.server.secure.xframeoptions | default "SAMEORIGIN" }}
  DATUM.SERVER.SECURE_HSTSPRELOADENABLED: {{ .Values.datum.server.secure.hstspreloadenabled | default false }}
  DATUM.SERVER.SECURE_HSTSMAXAGE: {{ .Values.datum.server.secure.hstsmaxage | default 31536000 }}
  DATUM.SERVER.SECURE_CONTENTSECURITYPOLICY: {{ .Values.datum.server.secure.contentsecuritypolicy | default "default-src 'self'" }}
  DATUM.SERVER.SECURE_REFERRERPOLICY: {{ .Values.datum.server.secure.referrerpolicy | default "same-origin" }}
  DATUM.SERVER.SECURE_CSPREPORTONLY: {{ .Values.datum.server.secure.cspreportonly | default false }}
  DATUM.SERVER.REDIRECTS_ENABLED: {{ .Values.datum.server.redirects.enabled | default true }}
  DATUM.SERVER.REDIRECTS_REDIRECTS: {{ .Values.datum.server.redirects.redirects }}
  DATUM.SERVER.REDIRECTS_CODE: {{ .Values.datum.server.redirects.code }}
  DATUM.SERVER.CACHECONTROL_ENABLED: {{ .Values.datum.server.cacheControl.enabled | default true }}
  DATUM.SERVER.CACHECONTROL_NOCACHEHEADERS: {{ .Values.datum.server.cacheControl.noCacheHeaders }}
  DATUM.SERVER.CACHECONTROL_ETAGHEADERS: {{ .Values.datum.server.cacheControl.etagHeaders }}
  DATUM.SERVER.MIME_ENABLED: {{ .Values.datum.server.mime.enabled | default true }}
  DATUM.SERVER.MIME_MIMETYPESFILE: {{ .Values.datum.server.mime.mimeTypesFile }}
  DATUM.SERVER.MIME_DEFAULTCONTENTTYPE: {{ .Values.datum.server.mime.defaultContentType | default "application/data" }}
  DATUM.AUTH_ENABLED: {{ .Values.datum.auth.enabled | default true }}
  DATUM.AUTH.TOKEN_KID: {{ .Values.datum.auth.token.kid }}
  DATUM.AUTH.TOKEN_AUDIENCE: {{ .Values.datum.auth.token.audience | default "https://datum.net" }}
  DATUM.AUTH.TOKEN_REFRESHAUDIENCE: {{ .Values.datum.auth.token.refreshAudience }}
  DATUM.AUTH.TOKEN_ISSUER: {{ .Values.datum.auth.token.issuer | default "https://auth.datum.net" }}
  DATUM.AUTH.TOKEN_ACCESSDURATION: {{ .Values.datum.auth.token.accessDuration | default "1h" }}
  DATUM.AUTH.TOKEN_REFRESHDURATION: {{ .Values.datum.auth.token.refreshDuration | default "2h" }}
  DATUM.AUTH.TOKEN_REFRESHOVERLAP: {{ .Values.datum.auth.token.refreshOverlap | default "-15m" }}
  DATUM.AUTH.TOKEN_JWKSENDPOINT: {{ .Values.datum.auth.token.jwksEndpoint | default "https://api.datum.net/.well-known/jwks.json" }}
  DATUM.AUTH.TOKEN_KEYS: {{ .Values.datum.auth.token.keys }}
  DATUM.AUTH.TOKEN_GENERATEKEYS: {{ .Values.datum.auth.token.generateKeys | default true }}
  DATUM.AUTH_SUPPORTEDPROVIDERS: {{ .Values.datum.auth.supportedProviders }}
  DATUM.AUTH.PROVIDERS_REDIRECTURL: {{ .Values.datum.auth.providers.redirectUrl | default "http://localhost:3001/api/auth/callback/datum" }}
  DATUM.AUTH.PROVIDERS.GITHUB_CLIENTID: {{ .Values.datum.auth.providers.github.clientId }}
  DATUM.AUTH.PROVIDERS.GITHUB_CLIENTSECRET: {{ .Values.datum.auth.providers.github.clientSecret }}
  DATUM.AUTH.PROVIDERS.GITHUB_CLIENTENDPOINT: {{ .Values.datum.auth.providers.github.clientEndpoint | default "http://localhost:17608" }}
  DATUM.AUTH.PROVIDERS.GITHUB_SCOPES: {{ .Values.datum.auth.providers.github.scopes }}
  DATUM.AUTH.PROVIDERS.GITHUB_REDIRECTURL: {{ .Values.datum.auth.providers.github.redirectUrl | default "/v1/github/callback" }}
  DATUM.AUTH.PROVIDERS.GOOGLE_CLIENTID: {{ .Values.datum.auth.providers.google.clientId }}
  DATUM.AUTH.PROVIDERS.GOOGLE_CLIENTSECRET: {{ .Values.datum.auth.providers.google.clientSecret }}
  DATUM.AUTH.PROVIDERS.GOOGLE_CLIENTENDPOINT: {{ .Values.datum.auth.providers.google.clientEndpoint | default "http://localhost:17608" }}
  DATUM.AUTH.PROVIDERS.GOOGLE_SCOPES: {{ .Values.datum.auth.providers.google.scopes }}
  DATUM.AUTH.PROVIDERS.GOOGLE_REDIRECTURL: {{ .Values.datum.auth.providers.google.redirectUrl | default "/v1/google/callback" }}
  DATUM.AUTH.PROVIDERS.WEBAUTHN_ENABLED: {{ .Values.datum.auth.providers.webauthn.enabled | default true }}
  DATUM.AUTH.PROVIDERS.WEBAUTHN_DISPLAYNAME: {{ .Values.datum.auth.providers.webauthn.displayName | default "Datum" }}
  DATUM.AUTH.PROVIDERS.WEBAUTHN_RELYINGPARTYID: {{ .Values.datum.auth.providers.webauthn.relyingPartyId | default "localhost" }}
  DATUM.AUTH.PROVIDERS.WEBAUTHN_REQUESTORIGIN: {{ .Values.datum.auth.providers.webauthn.requestOrigin | default "http://localhost:3001" }}
  DATUM.AUTH.PROVIDERS.WEBAUTHN_MAXDEVICES: {{ .Values.datum.auth.providers.webauthn.maxDevices | default 10 }}
  DATUM.AUTH.PROVIDERS.WEBAUTHN_ENFORCETIMEOUT: {{ .Values.datum.auth.providers.webauthn.enforceTimeout | default true }}
  DATUM.AUTH.PROVIDERS.WEBAUTHN_TIMEOUT: {{ .Values.datum.auth.providers.webauthn.timeout | default "60s" }}
  DATUM.AUTH.PROVIDERS.WEBAUTHN_DEBUG: {{ .Values.datum.auth.providers.webauthn.debug | default false }}
  DATUM.AUTHZ_ENABLED: {{ .Values.datum.authz.enabled | default true }}
  DATUM.AUTHZ_STORENAME: {{ .Values.datum.authz.storeName | default "datum" }}
  DATUM.AUTHZ_HOSTURL: {{ .Values.datum.authz.hostUrl | default "https://authz.datum.net" }}
  DATUM.AUTHZ_STOREID: {{ .Values.datum.authz.storeId }}
  DATUM.AUTHZ_MODELID: {{ .Values.datum.authz.modelId }}
  DATUM.AUTHZ_CREATENEWMODEL: {{ .Values.datum.authz.createNewModel | default false }}
  DATUM.AUTHZ_MODELFILE: {{ .Values.datum.authz.modelFile | default "fga/model/datum.fga" }}
  DATUM.DB_DEBUG: {{ .Values.datum.db.debug | default false }}
  DATUM.DB_DATABASENAME: {{ .Values.datum.db.databaseName | default "datum" }}
  DATUM.DB_DRIVERNAME: {{ .Values.datum.db.driverName | default "libsql" }}
  DATUM.DB_MULTIWRITE: {{ .Values.datum.db.multiWrite | default false }}
  DATUM.DB_PRIMARYDBSOURCE: {{ .Values.datum.db.primaryDbSource | default "file:datum.db" }}
  DATUM.DB_SECONDARYDBSOURCE: {{ .Values.datum.db.secondaryDbSource | default "file:backup.db" }}
  DATUM.DB_CACHETTL: {{ .Values.datum.db.cacheTTL | default "1s" }}
  DATUM.DB_RUNMIGRATIONS: {{ .Values.datum.db.runMigrations | default true }}
  DATUM.DB_MIGRATIONPROVIDER: {{ .Values.datum.db.migrationProvider | default "atlas" }}
  DATUM.DB_ENABLEHISTORY: {{ .Values.datum.db.enableHistory | default false }}
  DATUM.GEODETIC_ENABLED: {{ .Values.datum.geodetic.enabled | default true }}
  DATUM.GEODETIC_BASEURL: {{ .Values.datum.geodetic.baseUrl | default "http://localhost:1337" }}
  DATUM.GEODETIC_ENDPOINT: {{ .Values.datum.geodetic.endpoint | default "query" }}
  DATUM.GEODETIC_DEBUG: {{ .Values.datum.geodetic.debug | default false }}
  DATUM.REDIS_ENABLED: {{ .Values.datum.redis.enabled | default true }}
  DATUM.REDIS_ADDRESS: {{ .Values.datum.redis.address | default "localhost:6379" }}
  DATUM.REDIS_NAME: {{ .Values.datum.redis.name | default "datum" }}
  DATUM.REDIS_USERNAME: {{ .Values.datum.redis.username }}
  DATUM.REDIS_PASSWORD: {{ .Values.datum.redis.password }}
  DATUM.REDIS_DB: {{ .Values.datum.redis.db | default 0 }}
  DATUM.REDIS_DIALTIMEOUT: {{ .Values.datum.redis.dialTimeout | default "5s" }}
  DATUM.REDIS_READTIMEOUT: {{ .Values.datum.redis.readTimeout | default "0" }}
  DATUM.REDIS_WRITETIMEOUT: {{ .Values.datum.redis.writeTimeout | default "0" }}
  DATUM.REDIS_MAXRETRIES: {{ .Values.datum.redis.maxRetries | default 3 }}
  DATUM.REDIS_MINIDLECONNS: {{ .Values.datum.redis.minIdleConns | default 0 }}
  DATUM.REDIS_MAXIDLECONNS: {{ .Values.datum.redis.maxIdleConns | default 0 }}
  DATUM.REDIS_MAXACTIVECONNS: {{ .Values.datum.redis.maxActiveConns | default 0 }}
  DATUM.TRACER_ENABLED: {{ .Values.datum.tracer.enabled | default false }}
  DATUM.TRACER_PROVIDER: {{ .Values.datum.tracer.provider | default "stdout" }}
  DATUM.TRACER_ENVIRONMENT: {{ .Values.datum.tracer.environment | default "development" }}
  DATUM.TRACER.STDOUT_PRETTY: {{ .Values.datum.tracer.stdout.pretty | default true }}
  DATUM.TRACER.STDOUT_DISABLETIMESTAMP: {{ .Values.datum.tracer.stdout.disableTimestamp | default false }}
  DATUM.TRACER.OTLP_ENDPOINT: {{ .Values.datum.tracer.otlp.endpoint | default "localhost:4317" }}
  DATUM.TRACER.OTLP_INSECURE: {{ .Values.datum.tracer.otlp.insecure | default true }}
  DATUM.TRACER.OTLP_CERTIFICATE: {{ .Values.datum.tracer.otlp.certificate }}
  DATUM.TRACER.OTLP_HEADERS: {{ .Values.datum.tracer.otlp.headers }}
  DATUM.TRACER.OTLP_COMPRESSION: {{ .Values.datum.tracer.otlp.compression }}
  DATUM.TRACER.OTLP_TIMEOUT: {{ .Values.datum.tracer.otlp.timeout | default "10s" }}
  DATUM.EMAIL_SENDGRIDAPIKEY: {{ .Values.datum.email.sendGridApiKey }}
  DATUM.EMAIL_FROMEMAIL: {{ .Values.datum.email.fromEmail | default "no-reply@datum.net" }}
  DATUM.EMAIL_TESTING: {{ .Values.datum.email.testing | default true }}
  DATUM.EMAIL_ARCHIVE: {{ .Values.datum.email.archive }}
  DATUM.EMAIL_DATUMLISTID: {{ .Values.datum.email.datumListId }}
  DATUM.EMAIL_ADMINEMAIL: {{ .Values.datum.email.adminEmail | default "admins@datum.net" }}
  DATUM.EMAIL.CONSOLEURL_CONSOLEBASE: {{ .Values.datum.email.consoleUrl.consoleBase | default "https://console.datum.net" }}
  DATUM.EMAIL.CONSOLEURL_VERIFY: {{ .Values.datum.email.consoleUrl.verify | default "/verify" }}
  DATUM.EMAIL.CONSOLEURL_INVITE: {{ .Values.datum.email.consoleUrl.invite | default "/invite" }}
  DATUM.EMAIL.CONSOLEURL_RESET: {{ .Values.datum.email.consoleUrl.reset | default "/password-reset" }}
  DATUM.EMAIL.MARKETINGURL_MARKETINGBASE: {{ .Values.datum.email.marketingUrl.marketingBase | default "https://www.datum.net" }}
  DATUM.EMAIL.MARKETINGURL_SUBSCRIBERVERIFY: {{ .Values.datum.email.marketingUrl.subscriberVerify | default "/verify" }}
  DATUM.EMAIL.MARKETINGURL_DEFAULTSUBSCRIPTIONORG: {{ .Values.datum.email.marketingUrl.defaultSubscriptionOrg | default "Datum" }}
  DATUM.SESSIONS_SIGNINGKEY: {{ .Values.datum.sessions.signingKey | default "my-signing-secret" }}
  DATUM.SESSIONS_ENCRYPTIONKEY: {{ .Values.datum.sessions.encryptionKey | default "encryptionsecret" }}
  DATUM.SENTRY_ENABLED: {{ .Values.datum.sentry.enabled | default false }}
  DATUM.SENTRY_DSN: {{ .Values.datum.sentry.dsn }}
  DATUM.SENTRY_ENVIRONMENT: {{ .Values.datum.sentry.environment | default "development" }}
  DATUM.SENTRY_ENABLETRACING: {{ .Values.datum.sentry.enableTracing | default false }}
  DATUM.SENTRY_TRACESAMPLER: {{ .Values.datum.sentry.traceSampler | default 1.0 }}
  DATUM.SENTRY_ATTACHSTACKTRACE: {{ .Values.datum.sentry.attachStacktrace | default true }}
  DATUM.SENTRY_SAMPLERATE: {{ .Values.datum.sentry.sampleRate | default 0.2 }}
  DATUM.SENTRY_TRACESAMPLERATE: {{ .Values.datum.sentry.traceSampleRate | default 0.2 }}
  DATUM.SENTRY_PROFILESAMPLERATE: {{ .Values.datum.sentry.profileSampleRate | default 0.2 }}
  DATUM.SENTRY_REPANIC: {{ .Values.datum.sentry.repanic }}
  DATUM.SENTRY_DEBUG: {{ .Values.datum.sentry.debug | default false }}
  DATUM.SENTRY_SERVERNAME: {{ .Values.datum.sentry.serverName }}
  DATUM.POSTHOG_ENABLED: {{ .Values.datum.posthog.enabled | default false }}
  DATUM.POSTHOG_APIKEY: {{ .Values.datum.posthog.apiKey }}
  DATUM.POSTHOG_HOST: {{ .Values.datum.posthog.host | default "https://app.posthog.com" }}
  DATUM.TOTP_ENABLED: {{ .Values.datum.totp.enabled | default true }}
  DATUM.TOTP_CODELENGTH: {{ .Values.datum.totp.codeLength | default 6 }}
  DATUM.TOTP_ISSUER: {{ .Values.datum.totp.issuer | default "datum" }}
  DATUM.TOTP_REDIS: {{ .Values.datum.totp.redis | default true }}
  DATUM.TOTP_SECRET: {{ .Values.datum.totp.secret }}
  DATUM.TOTP_RECOVERYCODECOUNT: {{ .Values.datum.totp.recoveryCodeCount | default 16 }}
  DATUM.TOTP_RECOVERYCODELENGTH: {{ .Values.datum.totp.recoveryCodeLength | default 8 }}
  DATUM.RATELIMIT_ENABLED: {{ .Values.datum.ratelimit.enabled | default false }}
  DATUM.RATELIMIT_LIMIT: {{ .Values.datum.ratelimit.limit | default 10 }}
  DATUM.RATELIMIT_BURST: {{ .Values.datum.ratelimit.burst | default 30 }}
  DATUM.RATELIMIT_EXPIRES: {{ .Values.datum.ratelimit.expires | default "10m" }}
  DATUM.OBJSTORAGE.S3_ENABLED: {{ .Values.datum.objstorage.s3.enabled | default false }}
  DATUM.OBJSTORAGE.S3_ACCESSKEYID: {{ .Values.datum.objstorage.s3.accessKeyID }}
  DATUM.OBJSTORAGE.S3_BUCKET: {{ .Values.datum.objstorage.s3.bucket | default "yourbucketname" }}
  DATUM.OBJSTORAGE.S3_ENDPOINT: {{ .Values.datum.objstorage.s3.endpoint }}
  DATUM.OBJSTORAGE.S3_REGION: {{ .Values.datum.objstorage.s3.region | default "us-region-a" }}
  DATUM.OBJSTORAGE.S3_SECRETACCESSKEY: {{ .Values.datum.objstorage.s3.secretAccessKey }}
  DATUM.OBJSTORAGE.S3_UPLOADCONCURRENCY: {{ .Values.datum.objstorage.s3.uploadConcurrency | default 5 }}
  DATUM.OBJSTORAGE.GCS_ENABLED: {{ .Values.datum.objstorage.gcs.enabled | default false }}
  DATUM.OBJSTORAGE.GCS_CREDENTIALSFILE: {{ .Values.datum.objstorage.gcs.credentialsFile | default "./credentials.json" }}
  DATUM.OBJSTORAGE.GCS_BUCKET: {{ .Values.datum.objstorage.gcs.bucket | default "yourbucketname" }}
  DATUM.OBJSTORAGE.FS_ENABLED: {{ .Values.datum.objstorage.fs.enabled | default false }}
  DATUM.OBJSTORAGE.FS_ROOT: {{ .Values.datum.objstorage.fs.root | default "./storage" }}
  DATUM.PUBLISHERCONFIG_ENABLED: {{ .Values.datum.publisherConfig.enabled | default false }}
  DATUM.PUBLISHERCONFIG_APPNAME: {{ .Values.datum.publisherConfig.appName | default "datum" }}
  DATUM.PUBLISHERCONFIG_ADDRESS: {{ .Values.datum.publisherConfig.address | default "localhost:10000" }}
  DATUM.PUBLISHERCONFIG_ADDRESSES: {{ .Values.datum.publisherConfig.addresses | default "localhost:10000" }}
  DATUM.PUBLISHERCONFIG_DEBUG: {{ .Values.datum.publisherConfig.debug | default false }}
