# db settings
db:
  debug: true
  multiWrite: false

# auth settings
auth:
  enabled: true
  supportedProviders:
    - google
    - github
  providers:
    google:
      scopes:
        - email
        - profile
    github:
      scopes:
        - user:email
        - read:user
    webauthn:
      debug: false
      enabled: true
      relyingPartyId: "api.datum.net"
      requestOrigins:
        - "https://console.datum.net"

# authz settings
authz:
  enabled: true
  storeName: datum

# email settings
email:
  testing: false
  consoleUrl:
    consoleBase: "https://console.datum.net"

# analytics settings
posthog:
  enabled: true
