auth:
    enabled: false
    providers:
        github:
            clientEndpoint: ""
            clientId: ""
            clientSecret: ""
            redirectUrl: ""
            scopes: null
        google:
            clientEndpoint: ""
            clientId: ""
            clientSecret: ""
            redirectUrl: ""
            scopes: null
        redirectUrl: ""
        webauthn:
            debug: false
            displayName: ""
            enabled: false
            enforceTimeout: false
            maxDevices: 0
            relyingPartyId: ""
            requestOrigin: ""
            timeout: 0
    supportedProviders: null
    token:
        accessDuration: 0
        audience: ""
        issuer: ""
        jwksEndpoint: ""
        keys: null
        kid: ""
        refreshAudience: ""
        refreshDuration: 0
        refreshOverlap: 0
authz:
    createNewModel: false
    enabled: false
    hostUrl: ""
    modelId: ""
    storeId: ""
    storeName: ""
db:
    catchTTL: 0
    databaseName: ""
    debug: false
    driverName: ""
    multiWrite: false
    primaryDbSource: ""
    runMigrations: false
    secondaryDbSource: ""
email:
    adminEmail: ""
    archive: ""
    datumListId: ""
    fromEmail: ""
    sendGridApiKey: ""
    testing: false
posthog:
    apiKey: ""
    enabled: false
    host: ""
redis:
    address: ""
    db: 0
    dialTimeout: 0
    enabled: false
    maxActiveConns: 0
    maxIdleConns: 0
    maxRetries: 0
    minIdleConns: 0
    name: ""
    password: ""
    readTimeout: 0
    username: ""
    writeTimeout: 0
refreshInterval: 0
sentry:
    attachStacktrace: false
    debug: false
    dsn: ""
    enableTracing: false
    enabled: false
    environment: ""
    profileSampleRate: 0
    repanic: false
    sampleRate: 0
    serverName: ""
    traceSampleRate: 0
    traceSampler: 0
server:
    cors:
        allowOrigins: null
        cookieInsecure: false
    debug: false
    dev: false
    idleTimeout: 0
    listen: ""
    readHeaderTimeout: 0
    readTimeout: 0
    shutdownGracePeriod: 0
    tls:
        autoCert: false
        certFile: ""
        certKey: ""
        config: null
        enabled: false
    writeTimeout: 0
sessions:
    encryptionKey: ""
    signingKey: ""
tracer:
    enabled: false
    environment: ""
    otlp:
        certificate: ""
        compression: ""
        endpoint: ""
        headers: null
        insecure: false
        timeout: 0
    provider: ""
    stdout:
        disableTimestamp: false
        pretty: false
