---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . -}}-config
  {{ $labels := include "common.tplvalues.merge" (dict "values" ( list .Values.api.commonLabels (include "common.labels.standard" .) ) "context" . ) }}
  labels: {{- include "common.tplvalues.render" ( dict "value" $labels "context" $) | nindent 4 }}
  {{- if .Values.api.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.api.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
data:
  DATUM_REFRESHINTERVAL: {{ .Values.datum.refreshInterval | default "10m" }}
  DATUM_SERVER_DEBUG: {{ .Values.datum.server.debug | default false }}
  DATUM_SERVER_DEV: {{ .Values.datum.server.dev | default false }}
  DATUM_SERVER_LISTEN: {{ .Values.datum.server.listen | default ":17608" }}
  DATUM_SERVER_SHUTDOWNGRACEPERIOD: {{ .Values.datum.server.shutdownGracePeriod | default "10s" }}
  DATUM_SERVER_READTIMEOUT: {{ .Values.datum.server.readTimeout | default "15s" }}
  DATUM_SERVER_WRITETIMEOUT: {{ .Values.datum.server.writeTimeout | default "15s" }}
  DATUM_SERVER_IDLETIMEOUT: {{ .Values.datum.server.idleTimeout | default "30s" }}
  DATUM_SERVER_READHEADERTIMEOUT: {{ .Values.datum.server.readHeaderTimeout | default "2s" }}
  DATUM_SERVER_TLS_ENABLED: {{ .Values.datum.server.tls.enabled | default false }}
  DATUM_SERVER_TLS_CERTFILE: {{ .Values.datum.server.tls.certFile | default "server.crt" }}
  DATUM_SERVER_TLS_CERTKEY: {{ .Values.datum.server.tls.certKey | default "server.key" }}
  DATUM_SERVER_TLS_AUTOCERT: {{ .Values.datum.server.tls.autoCert | default false }}
  DATUM_SERVER_CORS_ENABLED: {{ .Values.datum.server.cors.enabled | default true }}
  DATUM_SERVER_CORS_PREFIXES: {{ .Values.datum.server.cors.prefixes }}
  DATUM_SERVER_CORS_ALLOWORIGINS: {{ .Values.datum.server.cors.allowOrigins }}
  DATUM_SERVER_CORS_COOKIEINSECURE: {{ .Values.datum.server.cors.cookieInsecure }}
  DATUM_SERVER_SECURE_ENABLED: {{ .Values.datum.server.secure.enabled | default true }}
  DATUM_SERVER_SECURE_XSSPROTECTION: {{ .Values.datum.server.secure.xssprotection | default "1; mode=block" }}
  DATUM_SERVER_SECURE_CONTENTTYPENOSNIFF: {{ .Values.datum.server.secure.contenttypenosniff | default "nosniff" }}
  DATUM_SERVER_SECURE_XFRAMEOPTIONS: {{ .Values.datum.server.secure.xframeoptions | default "SAMEORIGIN" }}
  DATUM_SERVER_SECURE_HSTSPRELOADENABLED: {{ .Values.datum.server.secure.hstspreloadenabled | default false }}
  DATUM_SERVER_SECURE_HSTSMAXAGE: {{ .Values.datum.server.secure.hstsmaxage | default 31536000 }}
  DATUM_SERVER_SECURE_CONTENTSECURITYPOLICY: {{ .Values.datum.server.secure.contentsecuritypolicy | default "default-src 'self'" }}
  DATUM_SERVER_SECURE_REFERRERPOLICY: {{ .Values.datum.server.secure.referrerpolicy | default "same-origin" }}
  DATUM_SERVER_SECURE_CSPREPORTONLY: {{ .Values.datum.server.secure.cspreportonly | default false }}
  DATUM_SERVER_REDIRECTS_ENABLED: {{ .Values.datum.server.redirects.enabled | default true }}
  DATUM_SERVER_REDIRECTS_REDIRECTS: {{ .Values.datum.server.redirects.redirects }}
  DATUM_SERVER_REDIRECTS_CODE: {{ .Values.datum.server.redirects.code }}
  DATUM_SERVER_CACHECONTROL_ENABLED: {{ .Values.datum.server.cacheControl.enabled | default true }}
  DATUM_SERVER_CACHECONTROL_NOCACHEHEADERS: {{ .Values.datum.server.cacheControl.noCacheHeaders }}
  DATUM_SERVER_CACHECONTROL_ETAGHEADERS: {{ .Values.datum.server.cacheControl.etagHeaders }}
  DATUM_SERVER_MIME_ENABLED: {{ .Values.datum.server.mime.enabled | default true }}
  DATUM_SERVER_MIME_MIMETYPESFILE: {{ .Values.datum.server.mime.mimeTypesFile }}
  DATUM_SERVER_MIME_DEFAULTCONTENTTYPE: {{ .Values.datum.server.mime.defaultContentType | default "application/data" }}
  DATUM_SERVER_GRAPHPOOL_MAXWORKERS: {{ .Values.datum.server.graphPool.maxWorkers | default 100 }}
  DATUM_SERVER_GRAPHPOOL_MAXCAPACITY: {{ .Values.datum.server.graphPool.maxCapacity | default 1000 }}
  DATUM_AUTH_ENABLED: {{ .Values.datum.auth.enabled | default true }}
  DATUM_AUTH_TOKEN_KID: {{ .Values.datum.auth.token.kid }}
  DATUM_AUTH_TOKEN_AUDIENCE: {{ .Values.datum.auth.token.audience | default "https://datum.net" }}
  DATUM_AUTH_TOKEN_REFRESHAUDIENCE: {{ .Values.datum.auth.token.refreshAudience }}
  DATUM_AUTH_TOKEN_ISSUER: {{ .Values.datum.auth.token.issuer | default "https://auth.datum.net" }}
  DATUM_AUTH_TOKEN_ACCESSDURATION: {{ .Values.datum.auth.token.accessDuration | default "1h" }}
  DATUM_AUTH_TOKEN_REFRESHDURATION: {{ .Values.datum.auth.token.refreshDuration | default "2h" }}
  DATUM_AUTH_TOKEN_REFRESHOVERLAP: {{ .Values.datum.auth.token.refreshOverlap | default "-15m" }}
  DATUM_AUTH_TOKEN_JWKSENDPOINT: {{ .Values.datum.auth.token.jwksEndpoint | default "https://api.datum.net/.well-known/jwks.json" }}
  DATUM_AUTH_TOKEN_KEYS: {{ .Values.datum.auth.token.keys }}
  DATUM_AUTH_TOKEN_GENERATEKEYS: {{ .Values.datum.auth.token.generateKeys | default true }}
  DATUM_AUTH_SUPPORTEDPROVIDERS: {{ .Values.datum.auth.supportedProviders }}
  DATUM_AUTH_PROVIDERS_REDIRECTURL: {{ .Values.datum.auth.providers.redirectUrl | default "http://localhost:3001/api/auth/callback/datum" }}
  DATUM_AUTH_PROVIDERS_GITHUB_CLIENTID: {{ .Values.datum.auth.providers.github.clientId }}
  DATUM_AUTH_PROVIDERS_GITHUB_CLIENTSECRET: {{ .Values.datum.auth.providers.github.clientSecret }}
  DATUM_AUTH_PROVIDERS_GITHUB_CLIENTENDPOINT: {{ .Values.datum.auth.providers.github.clientEndpoint | default "http://localhost:17608" }}
  DATUM_AUTH_PROVIDERS_GITHUB_SCOPES: {{ .Values.datum.auth.providers.github.scopes }}
  DATUM_AUTH_PROVIDERS_GITHUB_REDIRECTURL: {{ .Values.datum.auth.providers.github.redirectUrl | default "/v1/github/callback" }}
  DATUM_AUTH_PROVIDERS_GOOGLE_CLIENTID: {{ .Values.datum.auth.providers.google.clientId }}
  DATUM_AUTH_PROVIDERS_GOOGLE_CLIENTSECRET: {{ .Values.datum.auth.providers.google.clientSecret }}
  DATUM_AUTH_PROVIDERS_GOOGLE_CLIENTENDPOINT: {{ .Values.datum.auth.providers.google.clientEndpoint | default "http://localhost:17608" }}
  DATUM_AUTH_PROVIDERS_GOOGLE_SCOPES: {{ .Values.datum.auth.providers.google.scopes }}
  DATUM_AUTH_PROVIDERS_GOOGLE_REDIRECTURL: {{ .Values.datum.auth.providers.google.redirectUrl | default "/v1/google/callback" }}
  DATUM_AUTH_PROVIDERS_WEBAUTHN_ENABLED: {{ .Values.datum.auth.providers.webauthn.enabled | default true }}
  DATUM_AUTH_PROVIDERS_WEBAUTHN_DISPLAYNAME: {{ .Values.datum.auth.providers.webauthn.displayName | default "Datum" }}
  DATUM_AUTH_PROVIDERS_WEBAUTHN_RELYINGPARTYID: {{ .Values.datum.auth.providers.webauthn.relyingPartyId | default "localhost" }}
  DATUM_AUTH_PROVIDERS_WEBAUTHN_REQUESTORIGIN: {{ .Values.datum.auth.providers.webauthn.requestOrigin | default "http://localhost:3001" }}
  DATUM_AUTH_PROVIDERS_WEBAUTHN_MAXDEVICES: {{ .Values.datum.auth.providers.webauthn.maxDevices | default 10 }}
  DATUM_AUTH_PROVIDERS_WEBAUTHN_ENFORCETIMEOUT: {{ .Values.datum.auth.providers.webauthn.enforceTimeout | default true }}
  DATUM_AUTH_PROVIDERS_WEBAUTHN_TIMEOUT: {{ .Values.datum.auth.providers.webauthn.timeout | default "60s" }}
  DATUM_AUTH_PROVIDERS_WEBAUTHN_DEBUG: {{ .Values.datum.auth.providers.webauthn.debug | default false }}
  DATUM_AUTHZ_ENABLED: {{ .Values.datum.authz.enabled | default true }}
  DATUM_AUTHZ_STORENAME: {{ .Values.datum.authz.storeName | default "datum" }}
  DATUM_AUTHZ_HOSTURL: {{ .Values.datum.authz.hostUrl | default "https://authz.datum.net" }}
  DATUM_AUTHZ_STOREID: {{ .Values.datum.authz.storeId }}
  DATUM_AUTHZ_MODELID: {{ .Values.datum.authz.modelId }}
  DATUM_AUTHZ_CREATENEWMODEL: {{ .Values.datum.authz.createNewModel | default false }}
  DATUM_AUTHZ_MODELFILE: {{ .Values.datum.authz.modelFile | default "fga/model/datum.fga" }}
  DATUM_DB_DEBUG: {{ .Values.datum.db.debug | default false }}
  DATUM_DB_DATABASENAME: {{ .Values.datum.db.databaseName | default "datum" }}
  DATUM_DB_DRIVERNAME: {{ .Values.datum.db.driverName | default "libsql" }}
  DATUM_DB_MULTIWRITE: {{ .Values.datum.db.multiWrite | default false }}
  DATUM_DB_PRIMARYDBSOURCE: {{ .Values.datum.db.primaryDbSource | default "file:datum.db" }}
  DATUM_DB_SECONDARYDBSOURCE: {{ .Values.datum.db.secondaryDbSource | default "file:backup.db" }}
  DATUM_DB_CACHETTL: {{ .Values.datum.db.cacheTTL | default "1s" }}
  DATUM_DB_RUNMIGRATIONS: {{ .Values.datum.db.runMigrations | default true }}
  DATUM_DB_MIGRATIONPROVIDER: {{ .Values.datum.db.migrationProvider | default "atlas" }}
  DATUM_DB_ENABLEHISTORY: {{ .Values.datum.db.enableHistory | default false }}
  DATUM_GEODETIC_ENABLED: {{ .Values.datum.geodetic.enabled | default true }}
  DATUM_GEODETIC_BASEURL: {{ .Values.datum.geodetic.baseUrl | default "http://localhost:1337" }}
  DATUM_GEODETIC_ENDPOINT: {{ .Values.datum.geodetic.endpoint | default "query" }}
  DATUM_GEODETIC_DEBUG: {{ .Values.datum.geodetic.debug | default false }}
  DATUM_REDIS_ENABLED: {{ .Values.datum.redis.enabled | default true }}
  DATUM_REDIS_ADDRESS: {{ .Values.datum.redis.address | default "localhost:6379" }}
  DATUM_REDIS_NAME: {{ .Values.datum.redis.name | default "datum" }}
  DATUM_REDIS_USERNAME: {{ .Values.datum.redis.username }}
  DATUM_REDIS_PASSWORD: {{ .Values.datum.redis.password }}
  DATUM_REDIS_DB: {{ .Values.datum.redis.db | default 0 }}
  DATUM_REDIS_DIALTIMEOUT: {{ .Values.datum.redis.dialTimeout | default "5s" }}
  DATUM_REDIS_READTIMEOUT: {{ .Values.datum.redis.readTimeout | default "0" }}
  DATUM_REDIS_WRITETIMEOUT: {{ .Values.datum.redis.writeTimeout | default "0" }}
  DATUM_REDIS_MAXRETRIES: {{ .Values.datum.redis.maxRetries | default 3 }}
  DATUM_REDIS_MINIDLECONNS: {{ .Values.datum.redis.minIdleConns | default 0 }}
  DATUM_REDIS_MAXIDLECONNS: {{ .Values.datum.redis.maxIdleConns | default 0 }}
  DATUM_REDIS_MAXACTIVECONNS: {{ .Values.datum.redis.maxActiveConns | default 0 }}
  DATUM_TRACER_ENABLED: {{ .Values.datum.tracer.enabled | default false }}
  DATUM_TRACER_PROVIDER: {{ .Values.datum.tracer.provider | default "stdout" }}
  DATUM_TRACER_ENVIRONMENT: {{ .Values.datum.tracer.environment | default "development" }}
  DATUM_TRACER_STDOUT_PRETTY: {{ .Values.datum.tracer.stdout.pretty | default true }}
  DATUM_TRACER_STDOUT_DISABLETIMESTAMP: {{ .Values.datum.tracer.stdout.disableTimestamp | default false }}
  DATUM_TRACER_OTLP_ENDPOINT: {{ .Values.datum.tracer.otlp.endpoint | default "localhost:4317" }}
  DATUM_TRACER_OTLP_INSECURE: {{ .Values.datum.tracer.otlp.insecure | default true }}
  DATUM_TRACER_OTLP_CERTIFICATE: {{ .Values.datum.tracer.otlp.certificate }}
  DATUM_TRACER_OTLP_HEADERS: {{ .Values.datum.tracer.otlp.headers }}
  DATUM_TRACER_OTLP_COMPRESSION: {{ .Values.datum.tracer.otlp.compression }}
  DATUM_TRACER_OTLP_TIMEOUT: {{ .Values.datum.tracer.otlp.timeout | default "10s" }}
  DATUM_EMAIL_SENDGRIDAPIKEY: {{ .Values.datum.email.sendGridApiKey }}
  DATUM_EMAIL_FROMEMAIL: {{ .Values.datum.email.fromEmail | default "no-reply@datum.net" }}
  DATUM_EMAIL_TESTING: {{ .Values.datum.email.testing | default true }}
  DATUM_EMAIL_ARCHIVE: {{ .Values.datum.email.archive }}
  DATUM_EMAIL_DATUMLISTID: {{ .Values.datum.email.datumListId }}
  DATUM_EMAIL_ADMINEMAIL: {{ .Values.datum.email.adminEmail | default "admins@datum.net" }}
  DATUM_EMAIL_CONSOLEURL_CONSOLEBASE: {{ .Values.datum.email.consoleUrl.consoleBase | default "https://console.datum.net" }}
  DATUM_EMAIL_CONSOLEURL_VERIFY: {{ .Values.datum.email.consoleUrl.verify | default "/verify" }}
  DATUM_EMAIL_CONSOLEURL_INVITE: {{ .Values.datum.email.consoleUrl.invite | default "/invite" }}
  DATUM_EMAIL_CONSOLEURL_RESET: {{ .Values.datum.email.consoleUrl.reset | default "/password-reset" }}
  DATUM_EMAIL_MARKETINGURL_MARKETINGBASE: {{ .Values.datum.email.marketingUrl.marketingBase | default "https://www.datum.net" }}
  DATUM_EMAIL_MARKETINGURL_SUBSCRIBERVERIFY: {{ .Values.datum.email.marketingUrl.subscriberVerify | default "/verify" }}
  DATUM_EMAIL_MARKETINGURL_DEFAULTSUBSCRIPTIONORG: {{ .Values.datum.email.marketingUrl.defaultSubscriptionOrg | default "Datum" }}
  DATUM_SESSIONS_SIGNINGKEY: {{ .Values.datum.sessions.signingKey | default "my-signing-secret" }}
  DATUM_SESSIONS_ENCRYPTIONKEY: {{ .Values.datum.sessions.encryptionKey | default "encryptionsecret" }}
  DATUM_SESSIONS_DOMAIN: {{ .Values.datum.sessions.domain }}
  DATUM_SENTRY_ENABLED: {{ .Values.datum.sentry.enabled | default false }}
  DATUM_SENTRY_DSN: {{ .Values.datum.sentry.dsn }}
  DATUM_SENTRY_ENVIRONMENT: {{ .Values.datum.sentry.environment | default "development" }}
  DATUM_SENTRY_ENABLETRACING: {{ .Values.datum.sentry.enableTracing | default false }}
  DATUM_SENTRY_TRACESAMPLER: {{ .Values.datum.sentry.traceSampler | default 1.0 }}
  DATUM_SENTRY_ATTACHSTACKTRACE: {{ .Values.datum.sentry.attachStacktrace | default true }}
  DATUM_SENTRY_SAMPLERATE: {{ .Values.datum.sentry.sampleRate | default 0.2 }}
  DATUM_SENTRY_TRACESAMPLERATE: {{ .Values.datum.sentry.traceSampleRate | default 0.2 }}
  DATUM_SENTRY_PROFILESAMPLERATE: {{ .Values.datum.sentry.profileSampleRate | default 0.2 }}
  DATUM_SENTRY_REPANIC: {{ .Values.datum.sentry.repanic }}
  DATUM_SENTRY_DEBUG: {{ .Values.datum.sentry.debug | default false }}
  DATUM_SENTRY_SERVERNAME: {{ .Values.datum.sentry.serverName }}
  DATUM_POSTHOG_ENABLED: {{ .Values.datum.posthog.enabled | default false }}
  DATUM_POSTHOG_APIKEY: {{ .Values.datum.posthog.apiKey }}
  DATUM_POSTHOG_HOST: {{ .Values.datum.posthog.host | default "https://app.posthog.com" }}
  DATUM_TOTP_ENABLED: {{ .Values.datum.totp.enabled | default true }}
  DATUM_TOTP_CODELENGTH: {{ .Values.datum.totp.codeLength | default 6 }}
  DATUM_TOTP_ISSUER: {{ .Values.datum.totp.issuer | default "datum" }}
  DATUM_TOTP_REDIS: {{ .Values.datum.totp.redis | default true }}
  DATUM_TOTP_SECRET: {{ .Values.datum.totp.secret }}
  DATUM_TOTP_RECOVERYCODECOUNT: {{ .Values.datum.totp.recoveryCodeCount | default 16 }}
  DATUM_TOTP_RECOVERYCODELENGTH: {{ .Values.datum.totp.recoveryCodeLength | default 8 }}
  DATUM_RATELIMIT_ENABLED: {{ .Values.datum.ratelimit.enabled | default false }}
  DATUM_RATELIMIT_LIMIT: {{ .Values.datum.ratelimit.limit | default 10 }}
  DATUM_RATELIMIT_BURST: {{ .Values.datum.ratelimit.burst | default 30 }}
  DATUM_RATELIMIT_EXPIRES: {{ .Values.datum.ratelimit.expires | default "10m" }}
  DATUM_OBJSTORAGE_S3_ENABLED: {{ .Values.datum.objstorage.s3.enabled | default false }}
  DATUM_OBJSTORAGE_S3_ACCESSKEYID: {{ .Values.datum.objstorage.s3.accessKeyID }}
  DATUM_OBJSTORAGE_S3_BUCKET: {{ .Values.datum.objstorage.s3.bucket | default "yourbucketname" }}
  DATUM_OBJSTORAGE_S3_ENDPOINT: {{ .Values.datum.objstorage.s3.endpoint }}
  DATUM_OBJSTORAGE_S3_REGION: {{ .Values.datum.objstorage.s3.region | default "us-region-a" }}
  DATUM_OBJSTORAGE_S3_SECRETACCESSKEY: {{ .Values.datum.objstorage.s3.secretAccessKey }}
  DATUM_OBJSTORAGE_S3_UPLOADCONCURRENCY: {{ .Values.datum.objstorage.s3.uploadConcurrency | default 5 }}
  DATUM_OBJSTORAGE_GCS_ENABLED: {{ .Values.datum.objstorage.gcs.enabled | default false }}
  DATUM_OBJSTORAGE_GCS_CREDENTIALSFILE: {{ .Values.datum.objstorage.gcs.credentialsFile | default "./credentials.json" }}
  DATUM_OBJSTORAGE_GCS_BUCKET: {{ .Values.datum.objstorage.gcs.bucket | default "yourbucketname" }}
  DATUM_OBJSTORAGE_FS_ENABLED: {{ .Values.datum.objstorage.fs.enabled | default false }}
  DATUM_OBJSTORAGE_FS_ROOT: {{ .Values.datum.objstorage.fs.root | default "./storage" }}
  DATUM_PUBLISHERCONFIG_ENABLED: {{ .Values.datum.publisherConfig.enabled | default false }}
  DATUM_PUBLISHERCONFIG_APPNAME: {{ .Values.datum.publisherConfig.appName | default "datum" }}
  DATUM_PUBLISHERCONFIG_ADDRESS: {{ .Values.datum.publisherConfig.address | default "localhost:10000" }}
  DATUM_PUBLISHERCONFIG_ADDRESSES: {{ .Values.datum.publisherConfig.addresses | default "localhost:10000" }}
  DATUM_PUBLISHERCONFIG_DEBUG: {{ .Values.datum.publisherConfig.debug | default false }}
