auth:
    enabled: false
    providers:
        github:
            clientEndpoint: ""
            clientId: ""
            clientSecret: ""
            redirectUrl: ""
            scopes: null
        google:
            clientEndpoint: ""
            clientId: ""
            clientSecret: ""
            redirectUrl: ""
            scopes: null
        redirectUrl: ""
        webauthn:
            debug: false
            displayName: ""
            enabled: false
            enforceTimeout: false
            maxDevices: 0
            relyingPartyId: ""
            requestOrigin: ""
            timeout: 0
    supportedProviders: null
    token:
        accessDuration: 0
        audience: ""
        issuer: ""
        jwksEndpoint: ""
        keys: null
        kid: ""
        refreshAudience: ""
        refreshDuration: 0
        refreshOverlap: 0
authz:
    createNewModel: false
    enabled: false
    hostUrl: ""
    modelId: ""
    storeId: ""
    storeName: ""
db:
    catchTTL: 0
    databaseName: ""
    debug: false
    driverName: ""
    multiWrite: false
    primaryDbSource: ""
    runMigrations: false
    secondaryDbSource: ""
email:
    adminEmail: ""
    archive: ""
    datumListId: ""
    fromEmail: ""
    sendGridApiKey: ""
    testing: false
    url:
        base: ""
        invite: ""
        reset: ""
        verify: ""
posthog:
    apiKey: ""
    enabled: false
    host: ""
ratelimit:
    burst: 0
    enabled: false
    expires: 0
    limit: 0
redis:
    address: ""
    db: 0
    dialTimeout: 0
    enabled: false
    maxActiveConns: 0
    maxIdleConns: 0
    maxRetries: 0
    minIdleConns: 0
    name: ""
    password: ""
    readTimeout: 0
    username: ""
    writeTimeout: 0
refreshInterval: 0
sentry:
    attachStacktrace: false
    debug: false
    dsn: ""
    enableTracing: false
    enabled: false
    environment: ""
    profileSampleRate: 0
    repanic: false
    sampleRate: 0
    serverName: ""
    traceSampleRate: 0
    traceSampler: 0
server:
    cacheControl:
        enabled: false
        etagHeaders: null
        noCacheHeaders: null
    cors:
        allowOrigins: null
        cookieInsecure: false
        enabled: false
        prefixes: null
    debug: false
    dev: false
    idleTimeout: 0
    listen: ""
    readHeaderTimeout: 0
    readTimeout: 0
    redirect:
        code: 0
        enabled: false
        redirects: null
    secure:
        contentsecuritypolicy: ""
        contenttypenosniff: ""
        cspreportonly: false
        enabled: false
        hstsmaxage: 0
        hstspreloadenabled: false
        referrerpolicy: ""
        xframeoptions: ""
        xssprotection: ""
    shutdownGracePeriod: 0
    tls:
        autoCert: false
        certFile: ""
        certKey: ""
        config: null
        enabled: false
    writeTimeout: 0
sessions:
    encryptionKey: ""
    signingKey: ""
totp:
    codeLength: 0
    enabled: false
    issuer: ""
    recoveryCodeCount: 0
    recoveryCodeLength: 0
    redis: false
    secret: ""
tracer:
    enabled: false
    environment: ""
    otlp:
        certificate: ""
        compression: ""
        endpoint: ""
        headers: null
        insecure: false
        timeout: 0
    provider: ""
    stdout:
        disableTimestamp: false
        pretty: false
