name: Test PR Target
on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
    branches:
       - '*'
jobs:
  get-pr:
  # Permissions to write comments on the pull request.
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Get User Permission
        id: checkAccess
        uses: actions-cool/check-user-permission@v2
        with:
          require: write
          username: ${{ github.triggering_actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # # Allow the job to continue for users with write permissions
      # # Users without write permissions either need the job triggered by someone with write permissions
      # # or to have the `run-ci` label added to their PR
      # - name: Check User Permission
      #   if: steps.checkAccess.outputs.require-result == 'false' && !contains(github.event.pull_request.labels.*.name, 'run-ci')
      #   run: |
      #     echo "${{ github.triggering_actor }} does not have permissions on this repo."
      #     echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
      #     echo "Job originally triggered by ${{ github.actor }}"
      #     exit 1
      # - name: Checkout code
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{  github.event.pull_request.head.sha }} # This is dangerous without the first access check
      # - uses: ariga/setup-atlas@v0
      #   with:
      #     cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN_U6L6P6 }}
      # - uses: ariga/atlas-action/migrate/lint@v1
      #   with:
      #     dir: 'file://db/migrations'
      #     dir-name: 'datum'
      #     dev-url: 'sqlite://dev?mode=memory'
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      # - uses: ariga/atlas-action/migrate/push@v1
      #   if: github.ref == 'refs/heads/main'
      #   with:
      #       dir: 'file://db/migrations'
      #       dir-name: 'datum'
      #       dev-url: 'sqlite://dev?mode=memory'
