name: turso
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -sSf https://atlasgo.sh | sh
          atlas schema apply --env turso --to file://db/migrations --dev-url "sqlite://file?mode=memory" --auto-approve
        env:
          TURSO_TOKEN: ${{ secrets.TURSO_TOKEN }}
          ATLAS_CLOUD_TOKEN: ${{ secrets.ATLAS_CLOUD_TOKEN_utTMdP }}