name: osv-scanner

on:
  push:

# Declare default permissions as read only.
permissions: read-all

jobs:
  scan-pr-attempt:
    uses: "google/osv-scanner/.github/workflows/osv-scanner-reusable-pr.yml@main"
    with: 
      scan-args: |-
        -r
        ./