package sentry

import (
	"strings"

	echo "github.com/datumforge/echox"
	"github.com/getsentry/sentry-go"
)

func prepareTagValue(str string) string {
	size := 200 // limit of sentry

	str = strings.ReplaceAll(str, "\n", " ") // no \n in strings
	result := []rune(str)

	if len(result) <= size {
		return str
	}

	return string(result[:size-3]) + "..."
}

func prepareTagName(str string) string {
	size := 32 // limit of sentry
	result := []rune(str)

	if len(result) <= size {
		return str
	}

	return string(result[:size])
}

func setTag(span *sentry.Span, tag, value string) {
	if tag == "" || value == "" {
		return
	}

	span.SetTag(prepareTagName(tag), prepareTagValue(value))
}

func getRequestID(ctx echo.Context) string {
	requestID := ctx.Request().Header.Get(echo.HeaderXRequestID) // request-id generated by reverse-proxy
	if requestID == "" {
		// missed request-id from proxy, got generated one by middleware.RequestID()
		requestID = ctx.Response().Header().Get(echo.HeaderXRequestID)
	}

	return requestID
}
